### ISSUE TITLE
Proposal: Connect directly to facebook

### ISSUE THREAD

**Issue by Theo-** [Theo-/virtual-real-estate#13]
**Objectives**
- Get rid of the 5 seconds timeout bullshit
- Being able to initiate the conversation

**How to do it**
We need to plugin directly with the facebook API and use the API.ai SDK. Everything can be done in python.
Our bot will style use API.ai but only as a parser of the messenger that we receive. For example, every time our bot gets a message from facebook it will send it to API.ai for parsing and gather the intent and response (in the case where a slot needs to be filled).

**Links**
- api.ai SDK https://github.com/api-ai/api-ai-python
- facebook API https://developers.facebook.com/docs/messenger-platform

**Comment by taodav** [comment]
refer to latest PR:

fb_requests.py contains helper functions you can stick in app route decorators that has send message and receive message functionalities.

all we need to do is add api.ai sdk to this, then we'll have a working app.

Note if we refactor this code, we'll need to have our own switch statements for our responses with the intents. Api.ai won't handle that for us anymore because we'll be sending the messages out straight.

Maybe take a look at api.ai docs see if there's a middle ground?
